
package mp.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ModelException", targetNamespace = "http://manager.mp/")
public class ModelException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ModelException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ModelException_Exception(String message, ModelException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ModelException_Exception(String message, ModelException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mp.client.ModelException
     */
    public ModelException getFaultInfo() {
        return faultInfo;
    }

}
