
package mp.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ModelManagerService", targetNamespace = "http://manager.mp/", wsdlLocation = "http://localhost:8085/WS/modelService?WSDL")
public class ModelManagerService
    extends Service
{

    private final static URL MODELMANAGERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mp.client.ModelManagerService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mp.client.ModelManagerService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8085/WS/modelService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8085/WS/modelService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MODELMANAGERSERVICE_WSDL_LOCATION = url;
    }

    public ModelManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModelManagerService() {
        super(MODELMANAGERSERVICE_WSDL_LOCATION, new QName("http://manager.mp/", "ModelManagerService"));
    }

    /**
     * 
     * @return
     *     returns ModelManager
     */
    @WebEndpoint(name = "ModelManagerPort")
    public ModelManager getModelManagerPort() {
        return super.getPort(new QName("http://manager.mp/", "ModelManagerPort"), ModelManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModelManager
     */
    @WebEndpoint(name = "ModelManagerPort")
    public ModelManager getModelManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://manager.mp/", "ModelManagerPort"), ModelManager.class, features);
    }

}
